---
title: "Fifth blog post"
subtitle: ""
description:  |
  This blog post integrates Chicago crime data with 2023 census demographics to better understand racial and gender disparities in victimization. Initial findings highlight disproportionate impacts on Black individuals and women, with future steps focused on aligning race categories, merging datasets, and building visual analyses.
author: "BHZZ"
date: "2025-04-07"
categories: []
date-modified: "2025-04-07"
draft: FALSE
---

**Additional Dataset:**

    https://data.census.gov/table/ACSST1Y2023.S0601?q=Chicago+Demographics

We combined our violent crime victim data with 2023 ACS 1-Year estimates for Chicago, which provide demographic breakdowns of sex and race across the city.

**Combining the data:**

We can use the TIME_PERIOD, RACE, and AGE variables in the victim dataset to connect with the RACE, AGE, and YEAR variables in this demographics dataset. The new dataset containing the variables of marital status, education level, personal income, and poverty status would provide more information and probably give more insights into the reasons for the crime conviction.

**Initial findings:**

After briefly looking through the new dataset, we found that while the black individuals make up only 27.9% of the population, they account for over 50% of homicide and battery victims. Other than that, as females represent around 51.5% of the population, in the sexual assault crimes, they are disproportionately represented, which will be the part we will continue exploring the reasons behind. 

**Possible challenges and Next Steps:**

Since the race categorization in the new dataset is different from the victim data, and we are not quite sure about some race types in the victim data, it may be a problem we need to keep working on. 
And then we will start working on combining the data, making some visuals, and interpreting the results. 
