---
title: "Sixth blog post"
subtitle: ""
description:  |
  This blog post outlines the next priorities: completing an interactive Shiny dashboard and refining the Big Picture article to clearly communicate racial and gender disparities in Chicago crime data. Key next steps include polishing visual explanations, improving narrative flow, and finalizing the headline.
author: "BHZZ"
date: "2025-04-14"
categories: []
date-modified: "2025-04-14"
draft: FALSE
---

**Final Steps:**

As our team approaches the final stages of the project, we’ve assessed our progress to identify areas of the project where more work is needed. We've successfully conducted an indepth analysis and produced several charts/graphs highlighting demographic differences in violent crime victimization in Chicago. Our visuals include clear breakdowns by sex and race, and support a story about inequalities in crime victimization. We've also formulated a preliminary narrative thesis highlighting the significant disparities based on sex and race to form the foundation of the Big Picture article.

The first task we still need to complete is the interactive dashboard component. We have a template and dataset ready, but we still need to finalize our Shiny dashboard to make sure it supports our narrative by allowing users to explore different demographics interactively. Also, we're editing our Big Picture article’s to create an engaging, clear, and informative style similar to popular media. Next steps include finalizing a creative and engaging headline, finishing the explanatory text around each visualization, and making sure the interactive components flow with the narrative.


